# Generated by Django 4.2 on 2023-04-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='SurvivorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('contaminated', models.BooleanField(default=False)),
                ('amountAlerts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'survivors',
            },
        ),
    ]
