# Generated by Django 4.2 on 2023-04-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemmodel')),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survivormodel')),
            ],
            options={
                'db_table': 'inventories',
            },
        ),
    ]
