# Generated by Django 4.2 on 2023-04-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inventorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivormodel',
            old_name='amountAlerts',
            new_name='reports',
        ),
    ]
