# Generated by Django 4.2 on 2023-04-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_survivormodel_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='itemmodel',
            table=None,
        ),
    ]
