# Generated by Django 4.2 on 2023-04-07 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_itemmodel_options_alter_itemmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={},
        ),
    ]
