# Generated by Django 4.2 on 2023-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_itemmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivormodel',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
