# Generated by Django 4.2 on 2023-04-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_survivormodel_sex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmodel',
            table='items',
        ),
    ]
